In [6]:
import numpy as np 
import pandas as pd

In [7]:
df=pd.read_csv("data/employee_data.csv")

In [9]:
df.head()

,Employee_ID,Name,Gender,Age,Department,Designation,Experience_Years,Salary,Performance_Rating,Attendance,City,Joining_Date,Work_Mode,Overtime_Hours,Training_Hours
0,1001,Sneha Patel,Male,51,Sales,Intern,18,71015,GOOD,71.50,Bangalore,2020-11-18,OFFICE,21,9
1,1002,Rohan Jain,Male,40,it,senior Analyst,2,127877,average,88.10,chennai,2019-12-15,remote,13,41
2,1003,Rohan Gupta,M,44,Marketing,senior Analyst,6,40339,average,94.20,Bangalore,2019-11-19,remote,10,35
3,1004,Sneha mehta,M,45,HR,manager,13,28491,GOOD,74.71,Mumbai,2018-11-26,OFFICE,22,16
4,1005,aditya yadav,F,56,Sales,Intern,13,25706,GOOD,70.45,lucknow,2022-10-13,remote,10,39

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Employee_ID         1000 non-null   int64
 1   Name                1000 non-null   str
 2   Gender              1000 non-null   str
 3   Age                 1000 non-null   int64
 4   Department          1000 non-null   str
 5   Designation         1000 non-null   str
 6   Experience_Years    1000 non-null   int64
 7   Salary              1000 non-null   int64
 8   Performance_Rating  1000 non-null   str
 9   Attendance          1000 non-null   float64
 10  City                1000 non-null   str
 11  Joining_Date        1000 non-null   str
 12  Work_Mode           1000 non-null   str
 13  Overtime_Hours      1000 non-null   int64
 14  Training_Hours      1000 non-null   int64
dtypes: float64(1), int64(6), str(8)
memory usage: 117.3 KB

In [10]:
df.describe()

,Employee_ID,Age,Experience_Years,Salary,Attendance,Overtime_Hours,Training_Hours
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,1500.500000,40.379000,9.659000,87457.742000,85.306190,15.247000,26.754000
std,288.819436,11.108139,5.791741,35178.442004,8.714869,8.814061,13.187623
min,1001.000000,21.000000,0.000000,25229.000000,70.090000,0.000000,5.000000
25%,1250.750000,31.000000,5.000000,57220.750000,78.135000,8.000000,15.000000
50%,1500.500000,41.000000,10.000000,87523.500000,85.550000,15.000000,26.000000
75%,1750.250000,50.000000,15.000000,117843.750000,93.000000,23.000000,38.000000
max,2000.000000,59.000000,19.000000,149647.000000,99.950000,30.000000,50.000000

In [11]:
df.isna()

,Employee_ID,Name,Gender,Age,Department,Designation,Experience_Years,Salary,Performance_Rating,Attendance,City,Joining_Date,Work_Mode,Overtime_Hours,Training_Hours
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
996,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
997,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
998,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
999,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [12]:
df.isna().sum()

Employee_ID           0
Name                  0
Gender                0
Age                   0
Department            0
Designation           0
Experience_Years      0
Salary                0
Performance_Rating    0
Attendance            0
City                  0
Joining_Date          0
Work_Mode             0
Overtime_Hours        0
Training_Hours        0
dtype: int64

In [15]:
df["Name"].unique()

<StringArray>
[  'Sneha Patel',    'Rohan Jain',   'Rohan Gupta',   'Sneha mehta',
  'aditya yadav',     'Neha Jain',   'priya Patel',     'Riya Jain',
 'aditya Maurya',   'priya Verma',
 ...
    'Neha mehta',   'aarav Verma',  'Vivaan Kumar',  'Sneha Maurya',
    'Kabir Jain',   'Kabir Patel',   'aditya Jain',    'Neha Patel',
    'Neha yadav',   'Karan Gupta']
Length: 150, dtype: str

In [21]:
df["Name"] = df["Name"].replace({
    "Sneha mehta" : "Sneha Mehta",
    "aditya yadav": "Aditya Yadav",
    "priya Patel":"Priya Patel"})

df["Name"] = df["Name"].replace({
    "aditya Maurya": "Aditya Maurya",
    "priya Verma": "Priya Verma",
    "Neha mehta ": "Neha Mehta"})

df["Name"] = df["Name"].replace({
    "aarav Verma ": "Aarav Verma",
    "aditya Jain": "Aditya Jain",
    "Neha yadav": "Neha Yadav"
    })

In [22]:
df.head()

,Employee_ID,Name,Gender,Age,Department,Designation,Experience_Years,Salary,Performance_Rating,Attendance,City,Joining_Date,Work_Mode,Overtime_Hours,Training_Hours
0,1001,Sneha Patel,Male,51,Sales,Intern,18,71015,GOOD,71.50,Bangalore,2020-11-18,OFFICE,21,9
1,1002,Rohan Jain,Male,40,it,senior Analyst,2,127877,average,88.10,chennai,2019-12-15,remote,13,41
2,1003,Rohan Gupta,M,44,Marketing,senior Analyst,6,40339,average,94.20,Bangalore,2019-11-19,remote,10,35
3,1004,Sneha Mehta,M,45,HR,manager,13,28491,GOOD,74.71,Mumbai,2018-11-26,OFFICE,22,16
4,1005,Aditya Yadav,F,56,Sales,Intern,13,25706,GOOD,70.45,lucknow,2022-10-13,remote,10,39

In [25]:
df["Performance_Rating"].unique()

<StringArray>
['GOOD', 'average', 'excellent', 'Poor']
Length: 4, dtype: str

In [27]:
df["Performance_Rating"] = df["Performance_Rating"].replace({
    "GOOD" : "Good",
    "average": "Average",
    "excellent":"Excellent",
    "Poor":"Poor"
    })

In [28]:
df.head()

,Employee_ID,Name,Gender,Age,Department,Designation,Experience_Years,Salary,Performance_Rating,Attendance,City,Joining_Date,Work_Mode,Overtime_Hours,Training_Hours
0,1001,Sneha Patel,Male,51,Sales,Intern,18,71015,Good,71.50,Bangalore,2020-11-18,OFFICE,21,9
1,1002,Rohan Jain,Male,40,it,senior Analyst,2,127877,Average,88.10,chennai,2019-12-15,remote,13,41
2,1003,Rohan Gupta,M,44,Marketing,senior Analyst,6,40339,Average,94.20,Bangalore,2019-11-19,remote,10,35
3,1004,Sneha Mehta,M,45,HR,manager,13,28491,Good,74.71,Mumbai,2018-11-26,OFFICE,22,16
4,1005,Aditya Yadav,F,56,Sales,Intern,13,25706,Good,70.45,lucknow,2022-10-13,remote,10,39

In [29]:
df["Gender"].unique()

<StringArray>
['Male', 'M', 'F', 'male', 'female', 'Female']
Length: 6, dtype: str

In [31]:
    
df["Gender"] = df["Gender"].replace({
    "Male" : "M",
    "male": "M",
    "female":"F",
    "Female":"F"
    })

In [32]:
df.head()

,Employee_ID,Name,Gender,Age,Department,Designation,Experience_Years,Salary,Performance_Rating,Attendance,City,Joining_Date,Work_Mode,Overtime_Hours,Training_Hours
0,1001,Sneha Patel,M,51,Sales,Intern,18,71015,Good,71.50,Bangalore,2020-11-18,OFFICE,21,9
1,1002,Rohan Jain,M,40,it,senior Analyst,2,127877,Average,88.10,chennai,2019-12-15,remote,13,41
2,1003,Rohan Gupta,M,44,Marketing,senior Analyst,6,40339,Average,94.20,Bangalore,2019-11-19,remote,10,35
3,1004,Sneha Mehta,M,45,HR,manager,13,28491,Good,74.71,Mumbai,2018-11-26,OFFICE,22,16
4,1005,Aditya Yadav,F,56,Sales,Intern,13,25706,Good,70.45,lucknow,2022-10-13,remote,10,39

In [33]:
df["Department"].unique()

<StringArray>
['Sales', 'it', 'Marketing', 'HR', 'finance']
Length: 5, dtype: str

In [35]:
df["Department"] = df["Department"].replace({
    "it" : "IT",
    "finance": "Finance",
    })

In [36]:
df.head()

,Employee_ID,Name,Gender,Age,Department,Designation,Experience_Years,Salary,Performance_Rating,Attendance,City,Joining_Date,Work_Mode,Overtime_Hours,Training_Hours
0,1001,Sneha Patel,M,51,Sales,Intern,18,71015,Good,71.50,Bangalore,2020-11-18,OFFICE,21,9
1,1002,Rohan Jain,M,40,IT,senior Analyst,2,127877,Average,88.10,chennai,2019-12-15,remote,13,41
2,1003,Rohan Gupta,M,44,Marketing,senior Analyst,6,40339,Average,94.20,Bangalore,2019-11-19,remote,10,35
3,1004,Sneha Mehta,M,45,HR,manager,13,28491,Good,74.71,Mumbai,2018-11-26,OFFICE,22,16
4,1005,Aditya Yadav,F,56,Sales,Intern,13,25706,Good,70.45,lucknow,2022-10-13,remote,10,39

In [38]:
df["Designation"].unique()

<StringArray>
['Intern', 'senior Analyst', 'manager', 'EXecutive', 'Analyst']
Length: 5, dtype: str

In [52]:
df["Designation"] = df["Designation"].replace({
    "senior Analyst" : "Senior Analyst",
    "manager": "Manager",
    "EXecutive":"Executive"
    })

In [53]:
df.head()

,Employee_ID,Name,Gender,Age,Department,Designation,Experience_Years,Salary,Performance_Rating,Attendance,City,Joining_Date,Work_Mode,Overtime_Hours,Training_Hours
0,1001,Sneha Patel,M,51,Sales,Intern,18,71015,Good,71.50,Bangalore,2020-11-18,OFFICE,21,9
1,1002,Rohan Jain,M,40,IT,Senior Analyst,2,127877,Average,88.10,chennai,2019-12-15,remote,13,41
2,1003,Rohan Gupta,M,44,Marketing,Senior Analyst,6,40339,Average,94.20,Bangalore,2019-11-19,remote,10,35
3,1004,Sneha Mehta,M,45,HR,Manager,13,28491,Good,74.71,Mumbai,2018-11-26,OFFICE,22,16
4,1005,Aditya Yadav,F,56,Sales,Intern,13,25706,Good,70.45,lucknow,2022-10-13,remote,10,39

In [54]:
df["City"].unique()

<StringArray>
['Bangalore',   'chennai',    'Mumbai',   'lucknow', 'HyderaBad',    'Jaipur',
      'Pune',     'DELHI']
Length: 8, dtype: str

In [56]:
df["City"] = df["City"].replace({
    "chennai" : "Chennai",
    "lucknow": "Lucknow",
    "HyderaBad":"Hyderabad",
    "DELHI":"Delhi"

    })

In [57]:
df.head()

,Employee_ID,Name,Gender,Age,Department,Designation,Experience_Years,Salary,Performance_Rating,Attendance,City,Joining_Date,Work_Mode,Overtime_Hours,Training_Hours
0,1001,Sneha Patel,M,51,Sales,Intern,18,71015,Good,71.50,Bangalore,2020-11-18,OFFICE,21,9
1,1002,Rohan Jain,M,40,IT,Senior Analyst,2,127877,Average,88.10,Chennai,2019-12-15,remote,13,41
2,1003,Rohan Gupta,M,44,Marketing,Senior Analyst,6,40339,Average,94.20,Bangalore,2019-11-19,remote,10,35
3,1004,Sneha Mehta,M,45,HR,Manager,13,28491,Good,74.71,Mumbai,2018-11-26,OFFICE,22,16
4,1005,Aditya Yadav,F,56,Sales,Intern,13,25706,Good,70.45,Lucknow,2022-10-13,remote,10,39

In [61]:
df["Work_Mode"].unique()

<StringArray>
['OFFICE', 'remote', 'Hybrid']
Length: 3, dtype: str

In [64]:
df["Work_Mode"] = df["Work_Mode"].replace({
    "OFFICE" : "Office",
    "remote": "Remote",
    "HyderaBad":"Hyderabad",
    "DELHI":"Delhi"
})

In [65]:
df.head()

,Employee_ID,Name,Gender,Age,Department,Designation,Experience_Years,Salary,Performance_Rating,Attendance,City,Joining_Date,Work_Mode,Overtime_Hours,Training_Hours
0,1001,Sneha Patel,M,51,Sales,Intern,18,71015,Good,71.50,Bangalore,2020-11-18,Office,21,9
1,1002,Rohan Jain,M,40,IT,Senior Analyst,2,127877,Average,88.10,Chennai,2019-12-15,Remote,13,41
2,1003,Rohan Gupta,M,44,Marketing,Senior Analyst,6,40339,Average,94.20,Bangalore,2019-11-19,Remote,10,35
3,1004,Sneha Mehta,M,45,HR,Manager,13,28491,Good,74.71,Mumbai,2018-11-26,Office,22,16
4,1005,Aditya Yadav,F,56,Sales,Intern,13,25706,Good,70.45,Lucknow,2022-10-13,Remote,10,39

In [66]:
df.to_csv("data/cleaned_employee_data.csv", index=False)